[GS-332] deps: ember-composable-helpers@4.4.1
PrecisionNutrition/date-picker pull request #46
Opened 2020-12-21 19:50 UTC by typeoneerror

2020-12-21 20:56 UTC, typeoneerror commented
@jherdman bit of a rabbit hole here, but finally got this linted and passing. I think the canary is safe to ignore. looks like the same fails as FCR.

2020-12-22 14:39 UTC, jherdman commented
Works for me. I'm going to merge this. I'm going to merge a few more PRs here before you do a release (Prettier, Github Actions) today.

2020-12-22 14:41 UTC, jherdman requested changes
One note before I merge

2020-12-22 14:41 UTC, jherdman commented on package.json
> +    "ember-truth-helpers": "^2.1.0"
Can you discuss this change?

2020-12-22 15:30 UTC, merged